version: '3.9'

services:
  web:
    build: .
    container_name: drf_lms_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
      - db_data:/app/db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: unless-stopped

volumes:
  media:
  db_data:
